title: HBRL Research Group
remote_theme: alshedivat/al-folio@main
plugins:
  - jekyll-remote-theme
  - jekyll-scholar
  - jekyll-socials
  - jekyll-toc
baseurl: ""
url: "https://hbrleelab.github.io"
lang: en
future: true
